### ISSUE TITLE
Move VM Import functionality from VMIO into Migration Plan Controller

### ISSUE THREAD

**Issue by aufi** [kubev2v/forklift-controller#147]
# Introduction

The aim is to move vm-import functionality from Kubevirt's VMIO project to the Forklift controller. The new implementation should be driven by an Itinerary from Plan controller Migration and existing Plan&Migration CRs should be used.

Once the VM-import functionality is moved to Forklift, the VMIO project from Kubevirt (including its CRs) will be retired.

# Code move structure proposal

Forklift Itinerary phase | Code origin | Notes, dependencies, conditions
--- | --- | ---
Started |  | 
CreatePreHook | [forklift-controller/blob/main/pkg/controller/plan/migration.go](https://github.com/konveyor/forklift-controller/blob/main/pkg/controller/plan/migration.go) |
PreHookCreated | [forklift-controller/blob/main/pkg/controller/plan/migration.go](https://github.com/konveyor/forklift-controller/blob/main/pkg/controller/plan/migration.go) |
<del>Validate</del> | <del>[virtualmachineimport_controller.go#L332-L339](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L332-L339)</del> | Validation will be done by controller before entering the migration itinerary
StopVM | [virtualmachineimport_controller.go#L342-L347](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L342-L347) | unless WarmImport
PrepareVM | [virtualmachineimport_controller.go#L349-L364](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L349-L364) | <del>Could be splitted to more steps</del> [virtualmachineimport_controller.go#L728-L846](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L728-L846)
CreateDataVolumes | [virtualmachineimport_controller.go#L377-L387](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L377-L387) |
CreateDataVolumesCompleted | [virtualmachineimport_controller.go#L377-L387](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L377-L387) | 
AddDVCheckpoint | [virtualmachineimport_controller.go#L389-L399](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L389-L399) | if shouldWarmImport
DataVolumesCompleted | [virtualmachineimport_controller.go#L389-L399](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L389-L399) | 
ConvertGuest | [virtualmachineimport_controller.go#L401-L411](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L401-L411) |
ConvertGuestCompleted | [virtualmachineimport_controller.go#L401-L411](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L401-L411) | 
StartVM | [virtualmachineimport_controller.go#L419-L439](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L419-L439) |
ResourcesCleanup | [virtualmachineimport_controller.go#L419-L439](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L419-L439) | part of StartVM in VMIO
CreatePostHook | [forklift-controller/blob/main/pkg/controller/plan/migration.go](https://github.com/konveyor/forklift-controller/blob/main/pkg/controller/plan/migration.go) | 
PostHookCreated | [forklift-controller/blob/main/pkg/controller/plan/migration.go](https://github.com/konveyor/forklift-controller/blob/main/pkg/controller/plan/migration.go) | 
Completed |  | 

Code that can be dropped | not used | notes
--- | --- | --- 
VMIO PrepareProvider | [virtualmachineimport_controller.go#L291-L309](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L291-L309) | replace by existing Forklift Inventory

# Open questions
Emitted Events - needed to be kept?
https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L77-L98

Forklift CreateImport steps - https://github.com/konveyor/forklift-controller/blob/main/pkg/controller/plan/migration.go#L129-L173 - is there anything need to be preserved (secrets) or it should be fully covered by steps described above?

Work progress - I'd prefer create PRs with partial changes (new itinerary skeleton and making its steps working in several follow up PRs) to a new brach (proposing vmio_import name) and merge the branch to master/main once whole itinerary works without VMIO. Is OK/not-OK?

# Dependencies

The Forklift-controller currently requires VMIO as a dependency. Only dependencies required by the code moved to forklift-controller should be required instead of full VMIO.

# Related resources

* source: https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go (+underlaying packages)
* target: https://github.com/konveyor/forklift-controller/blob/main/pkg/controller/plan/migration.go

**Comment by jortel** [comment]
Why is this a separate controller?
What CR will this be reconciling?
Is there a design (at least high level) for this?

**Comment by aufi** [comment]
Thanks for feedback Jeff! The VMIO might need to be a separate project/repo (under Konveyor org, but close to current VMIO codebase, similar CR just updated to use migration toolkit shared concepts like Itinerary).

Sorry, I'm not sure at this moment, things are changing. Let's see (prepare high level design) after Monday call.

**Comment by mansam** [comment]
To answer the one open question, I don't think there's anything we'll need to keep from CreateImport. The secret it creates is just a requirement for VMIO which we will not need to worry about, since we won't need to retrieve anything from the source, and the inventory already has the credentials. I would expect the new steps to replace CreateImport entirely.

**Validate**:
I don't believe this will need to be a step in the itinerary. The Plan controller validates the resource mappings and VM references as part of the Plan reconcile, and I think validating that the source VM is migratable would fit there as well.

**PrepareVM**:
I think this will be able to be simplified greatly from VMIO. At this step we'd be pulling the VM representation out of the Forklift inventory and using that to create a Kubevirt VirtualMachine resource with no disks. We'll still have to have some provider specific code to map source VM properties to the destination, but hopefully a lot less since we're not going to need to go retrieve the VM properties like VMIO does. One open question here is whether or not we need to worry about Kubevirt templates. Hopefully we can just set the proper parameters on the Kubevirt VirtualMachine ourselves and skip the template entirely.

As an aside, VMIO uses resource names to keep track of resources that have been created for the import. Relying on names to identify resources requires the names to be deterministic or otherwise recorded somewhere on the parent resource, and tends to be flakey. Instead, we should use labels to identify resources we're creating (VM, datavolumes, etc).

**WarmImport/ImportDisks**:
These methods are huge in VMIO mostly due to the way that the reconcile runs, and we'll be able to simplfy them greatly.

Warm Import and Import Disks are very similar in that they're both creating a DataVolume, and waiting for that DataVolume to succeed. The difference is that during a warm import, the DataVolumes enter a `paused` state where they wait for their FinalCheckpoint value to be set to true, or for the next checkpoint to be added. Once this is done they go back to a `running` state. This can happen any number of times before the DataVolume eventually succeeds. A cold migration is effectively the same thing as a warm migration with no checkpoints. That being so, I think these can be streamlined together into one path. Probably one step would create the DataVolumes, and the next step would respond to the state changes by either waiting, creating the next checkpoint, or continuing to the next step once all DVs succeeded.

**ConvertGuest/ConvertGuestCompleted**:
This should be fairly simple to port in from VMIO. Mainly this is creating a configmap and a pod, and waiting for that pod to succeed. I think ConvertGuest is more descriptive of what it's doing than ConvertVM. (the virt-v2v pod is manipulating the guest OS filesystem to install drivers and such that are required to run in Kubevirt)
